### ISSUE TITLE
Slack Private Channels are not supported

### ISSUE THREAD

**Issue by tonythomas28** [katalon-studio/katalon-studio-slack-plugin#2]
When we enter a private channel name in the channel field its shows the message Connection Failed.

But When we enter a public channel name in the channel field its shows the Connection is successful.

**Comment by duyluonganh** [comment]
This issue has been resolved at commit https://github.com/katalon-studio/katalon-studio-slack-plugin/commit/363782bc287bd3cb45fad616047fd699d11a7e13

**Comment by kms-loantran** [comment]
verified and passed.
@tonythomas28: The new version of Slack plugin containing this fix is already uploaded to Store (https://store.katalon.com). Please reload this version in your KS tool and try it.

**Comment by duyluonganh** [comment]
The commit of this plugin is now available on KS Store
